### ISSUE TITLE
Feature Request: Integration with cmp

### ISSUE THREAD

**Issue by aemonge** [chrisgrieser/nvim-rulebook#6]
### Feature Requested

Integrate it with https://github.com/hrsh7th/nvim-cmp

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by chrisgrieser** [comment]
Just writing "integrate it with x" is really lazy writing. It does not specify what's kind of integration you are talking about, making it hard to work with. 

It's also a bit rude, since you expect an open source maintainer to do implement something for you which might take hours, while you yourself are not willing to spend an extra 20 seconds to explain your request. 

Given the lack of information I can just guess that you mean completion of ignore comments when typing close to a diagnostic? In that is the case, I will unfortunately pass, since that request is 
2. as opposed to the current mechanism which works for all users, issuing a completion plugin would only serve users of that particular plugin
3. has little benefit, since completions are slower than selecting from a choice is this case, and would also lack the forward-seeking behavior 
4. It is less future proof, while the current method will work for years to come, the completion approach needs to be overhauled every time there is a new completion plugin (right now, it looks like blink.cmp is gonna be the successor to cmp). 
5. Is also quite a bit of work to implement

**Comment by aemonge** [comment]
Hi @chrisgrieser,

    Firstly, I need to apologize with you. I was lazy to post the request, and that came out really rude. My intention were not to be this way, so again, I'm sorry.
    
    I want to contribute to your repository as an apology, but after reading your reasons of why to avoid the CMP completions, I don't know how to help you.
    
    If you think it would be beneficial to have an option to either use your own menu (as-is implemented) or to choose to use `vim.lsp.code_action` I would be more than happy to work this feature for you.

    Please let me know if there's another feature you think would be useful, and I can also work on it.
    
    By the way, I was fully unaware of `blink.cmp`, and I need to give you thanks for this, I'll be switching to it once it's more mature.

Thanks again for your polite response, and for your plugins.
